### ISSUE TITLE
Question—export to .pptx

### ISSUE THREAD

**Issue by atanasj** [iandol/scrivomatic#16]
Hi, 

Great scripting—this has really helped my workflow _**so much**_! 

I am having trouble exporting a slideshow. I cannot seem to get the `pandoc_title_block` to appear as would be expected when trying to go via the workflow.  

I have used the template provided in the `pandoc` [use manual](http://pandoc.org/MANUAL.html) (see the 'Producing slide shows with pandoc' section for the example `habits.txt` file).  

Specifically, this appears at the top of the document: 

```
% Habits
% John Doe
% March 22, 2005
```

The `cli` code provided in the manual is: 

```
pandoc habits.txt -o habits.pptx
```

This works as expected (see [habitsOk.pptx](https://github.com/iandol/scrivomatic/files/2238045/habitsOk.pptx)). Now, I have added the following to the `pandocomatic.yaml` file: 

```
  pptx:
    extends: ['refs']
    pandoc:
      from: markdown
      to: pptx
      reference-doc: "_templates/uow_custom.pptx"  #templates/custom.docx
``` 

All other attributes print as normal, however the title block does not (see  [habitsNotOk.pptx](https://github.com/iandol/scrivomatic/files/2238044/habitsNotOk.pptx)). I'm not sure whether it is because when going through the workflow it is converting form `markdown` and not `txt` as per the `pandoc` provided example, or something else completely different. 

Any ideas? Your help is greatly appreciated! 

Cheers, 
Atanas

**Comment by iandol** [comment]
Hi Atanas, that is an easy fix. The problem is that the sample markdown uses a title block for metadata, but pandocomatic uses YAML metadata, and you can't use both easily. As Pandoc fully supports the content of title block n YAML, if you format your metadata like so:

```yaml
---
title: Habits
author: Joanna Doe
date: March 22, 2005
pandocomatic:
  use-template: pptx
---
```

Then the title slide is also produced via pandocomatic :-)
